#!/usr/bin/env python
# coding: utf-8

# In[ ]:





# In[ ]:





# In[1]:


rats = ['cottage / swiss / cake',
 'cream / skate / water',
 'loser / throat / spot',
 'show / life / row',
 'night / wrist / stop',
 'duck / fold / dollar',
 'rocking / wheel / high',
 'dew / comb / bee',
 'fountain / baking / pop',
 'preserve / ranger / tropical',
 'aid / rubber / wagon',
 'flake / mobile / cone',
 'cracker / fly / fighter',
 'safety / cushion / point',
 'cane / daddy / plum',
 'dream / break / light',
 'fish / mine / rush',
 'political / surprise / line',
 'measure / worm / video',
 'high / district / house',
 'sense / courtesy / place',
 'worm / shelf / end',
 'piece / mind / dating',
 'flower / friend / scout',
 'river / note / account',
 'print / berry / bird',
 'pie / luck / belly',
 'date / alley / fold',
 'opera / hand / dish',
 'cadet / capsule / ship',
 'fur / rack / tail',
 'stick / maker / point',
 'hound / pressure / shot',
 'fox / man / peep',
 'sleeping / bean / trash',
 'dust / cereal / fish',
 'light / birthday / stick',
 'food / forward / break',
 'shine / beam / struck',
 'peach / arm / tar',
 'water / mine / shaker',
 'palm / shoe / house',
 'basket / eight / snow',
 'wheel / hand / shopping',
 'right / cat / carbon',
 'home / sea / bed',
 'nuclear / feud / album',
 'sandwich / house / golf',
 'cross / rain / tie',
 'sage / paint / hair',
 'french / car / shoe',
 'boot / summer / ground',
 'chamber / mask / natural',
 'mill / tooth / dust',
 'main / sweeper / light',
 'pike / coat / signal',
 'office / mail / hat',
 'fly / clip / wall',
 'age / mile / sand',
 'catcher / food / hot',
 'wagon / break / radio',
 'tank / hill / secret',
 'health / taker / less',
 'lift / card / mask',
 'dress / dial / flower',
 'force / line / mail',
 'guy / rain / down',
 'eight / skate / stick',
 'down / question / check',
 'animal / back / rat',
 'officer / cash / larceny',
 'pine / crab / sauce',
 'house / thumb / pepper',
 'carpet / alert / ink',
 'master / toss / finger',
 'hammer / gear / hunter',
 'knife / light / pal',
 'foul / ground / mate',
 'change / circuit / cake',
 'way / board / sleep',
 'blank / list / mate',
 'tail / water / flood',
 'marshal / child / piano',
 'cover / arm / wear',
 'rain / test / stomach',
 'time / blown / nelson',
 'pile / market / room',
 'mouse / bear / sand',
 'cat / number / phone',
 'keg / puff / room',
 'trip / house / goal',
 'fork / dark / man',
 'fence / card / master',
 'test / runner / map',
 'dive / light / rocket',
 'man / glue / star',
 'tooth / potato / heart',
 'illness / bus / computer',
 'type / ghost / screen',
 'mail / board / lung',
 'teeth / arrest / start',
 'iron / shovel / engine',
 'wet / law / business',
 'rope / truck / line',
 'off / military / first',
 'spoon / cloth / card',
 'cut / cream / war',
 'note / chain / master',
 'shock / shave / taste',
 'wise / work / tower',
 'grass / king / meat',
 'baby / spring / cap',
 'break / bean / cake',
 'cry / front / ship',
 'hold / print / stool',
 'roll / bean / fish',
 'horse / human / drag',
 'oil / bar / tuna',
 'bottom / curve / hop',
 'tomato / bomb / picker',
 'pea / shell / chest',
 'line / fruit / drunk',
 'bump / egg / step',
 'fight / control / machine',
 'home / arm / room',
 'child / scan / wash',
 'nose / stone / bear',
 'end / line / lock',
 'control / place / rate',
 'lounge / hour / napkin',
 'artist / hatch / route',
 'pet / bottom / garden',
 'mate / shoes / total',
 'self / attorney / spending',
 'board / blade / back',
 'land / hand / house',
 'hungry / order / belt',
 'forward / flush / razor',
 'shadow / chart / drop',
 'way / ground / weather',
 'cast / side / jump',
 'back / step / screen',
 'reading / service / stick',
 'over / plant / horse',
 'falling / actor / dust',
 'broken / clear / eye',
 'skunk / kings / boiled',
 'widow / bite / monkey',
 'bass / complex / sleep',
 'coin / quick / spoon',
 'gold / stool / tender',
 'time / hair / stretch',
 'cracker / union / rabbit',
 'bald / screech / emblem',
 'blood / music / cheese',
 'manners / round / tennis',
 'off / trumpet / atomic',
 'playing / credit / report',
 'rabbit / cloud / house',
 'room / blood / salts',
 'salt / deep / foam',
 'square / cardboard / open',
 'water / tobacco / stove',
 'ache / hunter / cabbage',
 'chamber / staff / box',
 'high / book / sour',
 'lick / sprinkle / mines',
 'pure / blue / fall',
 'snack / line / birthday',
 'square / telephone / club',
 'surprise / wrap / care',
 'ticket / shop / broker',
 'barrel / root / belly',
 'blade / witted / weary',
 'cherry / time / smell',
 'notch / flight / spin',
 'strap / pocket / time',
 'walker / main / sweeper',
 'wicked / bustle / slicker',
 'chocolate / fortune / tin',
 'color / numbers / oil',
 'mouse / sharp / blue',
 'sandwich / golf / foot',
 'silk / cream / even',
 'speak / money / street',
 'big / leaf / shade',
 'envy / golf / beans',
 'hall / car / swimming',
 'ink / herring / neck',
 'measure / desk / scotch',
 'strike / same / tennis',
 'athletes / web / rabbit',
 'board / magic / death',
 'lapse / vivid / elephant',
 'puss / tart / spoiled',
 'rock / times / steel',
 'stop / petty / sneak',
 'thread / pine / pain',
 'zone / still / noise',
 'cloth / sad / out',
 'cotton / bathtub / tonic',
 'foot / collection / out',
 'inch / deal / peg',
 'jump / kill / bliss',
 'magic / plush / floor',
 'note / dive / chair',
 'stalk / trainer / king',
 'bump / throat / sum',
 'shopping / washer / picture',
 'blank / white / lines',
 'stick / light / birthday',
 'sore / shoulder / sweat',
 'call / pay / line',
 'end / burning / blue',
 'man / hot / sure',
 'stick / pal / ball',
 'blue / cake / cottage',
 'man / wheel / high',
 'motion / poke / down',
 'line / birthday / surprise',
 'wood / liquor / luck',
 'house / village / golf',
 'plan / show / walker',
 'key / wall / previous',
 'bell / iron / tender',
 'water / youth / soda',
 'base / snow / dance',
 'stop / kart / slow',
 'up / book / charge',
 'tin / writer / my',
 'leg / arm / person',
 'weight / out / pencil',
 'spin / tip / shape',
 'sharp / tick / tie',
 'out / band / night',
 'cool / house / fat',
 'back / go / light',
 'man / order / air',
 'bath / up / burst',
 'ball / out / blue',
 'up / around / rear',
 'house / blanket / ball',
 'trap / polar / claw',
 'cinder / building / buster',
 'line / patrol / town',
 'thorn / whack / rose',
 'garbage / beer / paint',
 'scan / nap / burglar',
 'trap / back / screen',
 'through / disk / way',
 'tax / real / fourth',
 'life / color / coast',
 'wave / lamp / dry',
 'glass / rush / happy',
 'waffle / lung / tire',
 'poison / league / creeping',
 'pain / serial / whale',
 'floor / shade / heat',
 'puppy / TRUE / letter',
 'bedroom / plan / brew',
 'mouth / bike / oil',
 'polish / finger / down',
 'sake / pet / nick',
 'computer / cable / broadcast',
 'skirts / take / put',
 'jury / door / side',
 'due / life / tense',
 'tomato / cement / tooth',
 'flag / vault / fishing',
 'release / french / secretary',
 'dollar / stop / language',
 'quick / spoon / screen',
 'grand / door / bang',
 'dash / happy / stick',
 'ruby / glass / bunny',
 'demon / limit / way',
 'gap / door / sign',
 'food / front / drug',
 'set / program / cable',
 'chest / car / store',
 'property / moral / price',
 'rag / milk / out',
 'noise / collar / wash',
 'bay / picture / washer',
 'hard / drift / cutter',
 'cottage / brick / cake',
 'stick / hair / ball',
 'stool / powder / ball',
 'key / wall / precious',
 'water / pen / soda',
 'steady / cart / slow',
 'tin / write / my',
 'weight / pipe / pencil',
 'sharp / thumb / tie',
 'back / short / light',
 'bath / up / gum',
 'ball / out / jack',
 'up / deep / rear',
 'shelf / read / end',
 'sea / home / stomach',
 'car / swimming / cue',
 'cookies / sixteen / heart',
 'lounge / hour / drink',
 'keel / show / row',
 'desert / ice / spell',
 'base / show / dance',
 'soap / shoe / tissue',
 'hot / butterflies / pump',
 'head / street / dark',
 'room / saturday / salts',
 'surprise / line / birthday',
 'red / go / car']


# In[2]:


ans = ['cheese',
 'ice',
 'sore',
 'boat',
 'watch',
 'bill',
 'chair',
 'honey',
 'soda',
 'forest',
 'band',
 'snow',
 'fire',
 'pin',
 'sugar',
 'day',
 'gold',
 'party',
 'tape',
 'school',
 'common',
 'book',
 'game',
 'girl',
 'bank',
 'blue',
 'pot',
 'blind',
 'soap',
 'space',
 'coat',
 'match',
 'blood',
 'hole',
 'bag',
 'bowl',
 'candle',
 'fast',
 'moon',
 'pit',
 'salt',
 'tree',
 'ball',
 'cart',
 'copy',
 'sick',
 'family',
 'club',
 'bow',
 'brush',
 'horn',
 'camp',
 'gas',
 'saw',
 'street',
 'turn',
 'box',
 'paper',
 'stone',
 'dog',
 'station',
 'top',
 'care',
 'face',
 'sun',
 'air',
 'fall',
 'figure',
 'mark',
 'pack',
 'petty',
 'apple',
 'green',
 'red',
 'ring',
 'head',
 'pen',
 'play',
 'short',
 'walk',
 'check',
 'gate',
 'grand',
 'under',
 'acid',
 'full',
 'stock',
 'trap',
 'call',
 'powder',
 'field',
 'pitch',
 'post',
 'road',
 'sky',
 'super',
 'sweet',
 'terminal',
 'writer',
 'black',
 'false',
 'steam',
 'suit',
 'tow',
 'base',
 'table',
 'cold',
 'key',
 'after',
 'clock',
 'crab',
 'shower',
 'coffee',
 'battle',
 'foot',
 'jelly',
 'race',
 'salad',
 'bell',
 'cherry',
 'nut',
 'punch',
 'goose',
 'gun',
 'rest',
 'brain',
 'brown',
 'dead',
 'birth',
 'cocktail',
 'escape',
 'rock',
 'running',
 'defense',
 'switch',
 'farm',
 'money',
 'straight',
 'eye',
 'fair',
 'broad',
 'door',
 'lip',
 'power',
 'star',
 'glass',
 'cabbage',
 'spider',
 'deep',
 'silver',
 'bar',
 'long',
 'jack',
 'eagle',
 'blue',
 'table',
 'blast',
 'card',
 'white',
 'bath',
 'sea',
 'box',
 'pipe',
 'head',
 'music',
 'note',
 'salt',
 'water',
 'party',
 'book',
 'gift',
 'pawn',
 'beer',
 'dull',
 'blossom',
 'top',
 'watch',
 'street',
 'city',
 'cookie',
 'paint',
 'cheese',
 'club',
 'smooth',
 'easy',
 'tree',
 'green',
 'pool',
 'red',
 'tape',
 'match',
 'foot',
 'black',
 'memory',
 'sour',
 'hard',
 'thief',
 'needle',
 'quiet',
 'sack',
 'gin',
 'stamp',
 'square',
 'joy',
 'carpet',
 'high',
 'lion',
 'lump',
 'window',
 'paper',
 'candle',
 'cold',
 'phone',
 'book',
 'fire',
 'pin',
 'cheese',
 'chair',
 'slow',
 'party',
 'hard',
 'green',
 'floor',
 'stone',
 'bar',
 'fountain',
 'ball',
 'go',
 'cover',
 'type',
 'chair',
 'lead',
 'top',
 'tack',
 'watch',
 'cat',
 'stop',
 'mail',
 'bubble',
 'black',
 'end',
 'beach',
 'bear',
 'block',
 'border',
 'bush',
 'can',
 'cat',
 'door',
 'drive',
 'estate',
 'guard',
 'heat',
 'hour',
 'iron',
 'ivy',
 'killer',
 'lamp',
 'love',
 'master',
 'motor',
 'nail',
 'name',
 'network',
 'out',
 'panel',
 'past',
 'paste',
 'pole',
 'press',
 'sign',
 'silver',
 'slam',
 'slap',
 'slipper',
 'speed',
 'stop',
 'store',
 'television',
 'toy',
 'value',
 'weed',
 'white',
 'window',
 'wood',
 'cheese',
 'pin',
 'foot',
 'stone',
 'fountain',
 'go',
 'type',
 'lead',
 'tack',
 'stop',
 'bubble',
 'black',
 'end',
 'book',
 'sick',
 'pool',
 'sweet',
 'cocktail',
 'boat',
 'dry',
 'ball',
 'box',
 'stomach',
 'light',
 'bath',
 'party',
 'stop']


# In[3]:


import random
import asyncio
import aiohttp
import discord
from discord import Game
from discord.ext.commands import Bot

BOT_PREFIX = ("!")
TOKEN = "NDQxODM0OTEzOTU2ODg4NTg3.Dc2CYg.MmFbodsBq5pvQyDjO1K8QLqsQ1Y"  # Get at discordapp.com/developers/applications/me
#Debug Token
#TOKEN = 'NDQyMTU1MTU1OTkxOTUzNDE4.Dc6srg.hkYRdpkCQhjcN6BRMaM6qYYUOHY'
client = Bot(command_prefix=BOT_PREFIX,description='Play RAT games! !rat generates a new RAT, !answer \'guess\' submits \'guess\' as your answer.')
i=0

@client.command(name='rat',
               description='Generate RAT',
                brief='Generate RAT')
async def rat():
    global i
    i = random.randint(0,len(rats)-1)
    #i = 150
    await client.say(rats[i])
    
@client.command(name='rerat',
               description='Repeat previous RAT',
                brief='Repeat previous RAT')
async def rerat():
    await client.say(rats[i])
    
@client.command(name='answer',
               description='Use to submit a one-word answer',
                brief='Use to submit a one-word answer',
               pass_context=True)
async def answer(guess):
    right = ['Nice, ','Good job, ','Congratulations, ']
    wrong = ['That\'s not quite right...','Try again!','Keep thinking!']

    if ans[i] == guess.message.content.lower()[8:]: 
        await client.say(random.choice(right) + guess.message.author.mention + '! The correct answer is ' + ans[i] + '.')
    else:
        await client.say(random.choice(wrong))
    
@client.event
async def on_ready():
    await client.change_presence(game=Game(type=1,name="RAT games"))
    print("Logged in as " + client.user.name)

async def list_servers():
    await client.wait_until_ready()
    while not client.is_closed:
        print("Current servers:")
        for server in client.servers:
            print(server.name)
        await asyncio.sleep(600)

client.loop.create_task(list_servers())
client.run(TOKEN)


# In[ ]:


#DEBUG


# In[4]:


#rats.index('tooth / potato / heart')


# In[5]:


#ans[96]


# In[6]:


#rats[150]


# In[10]:


ans.index('box')


# In[8]:


#ans[150]


# 195, 150, 146, 56

# In[ ]:





# In[ ]:




